name: Release

on:
  workflow_dispatch:
    inputs:
      mode:
        description: "Release mode"
        type: choice
        options:
          - stable
          - dev
        default: stable

permissions:
  contents: write
  pull-requests: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: dtolnay/rust-toolchain@stable

      - uses: a-line-services/release-pilot@v1
        with:
          mode: ${{ inputs.mode }}
          cargo-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
